### ISSUE TITLE
its slow

### ISSUE THREAD

**Issue by NiaAxern** [GalvinPython/globalclicker#5]
slow
![image](https://github.com/GalvinPython/globalclicker/assets/66086765/1bf35430-d04a-4494-81ab-ba7731cf480d)

**Comment by GalvinPython** [comment]
The servers that my hosting provider use are terrible and aren't suitable for real-time interaction. Will be moving to a new backend system in the next couple of days. Should be more responsive

**Comment by GalvinPython** [comment]
Fixed

![image](https://github.com/GalvinPython/globalclicker/assets/77013913/cd095892-0e76-41d7-ad7d-26960ac89735)
